"""Authoritative source-backed crop requirement profiles from FAO ECOCROP.

Every threshold in this repository is directly traced to the Food and Agriculture
Organization (FAO) Crop Ecological Requirements Database (ECOCROP) and FAO GAEZ v4.
No agricultural threshold is invented, guessed, or imputed from general web articles.
"""

from __future__ import annotations

import copy
import logging
from typing import Dict

from app.services.farm_advisory.exceptions import CropRequirementNotFoundError
from app.services.farm_advisory.schemas import (
    CropEnvironmentalRequirement,
    RequirementProvenance,
)

logger = logging.getLogger(__name__)

# Standard FAO ECOCROP Provenance Header
DEFAULT_ECOCROP_PROVENANCE = RequirementProvenance(
    source_name="FAO ECOCROP - Crop Ecological Requirements Database",
    source_url="https://ecocrop.apps.fao.org/ecocrop/srv/en/home",
    source_field=(
        "TOPMN, TOPMX, TMIN, TMAX, ROPMN, ROPMX, RMIN, RMAX, "
        "PHOPMN, PHOPMX, PHMIN, PHMAX, TEXT, TEXTR, DRA, DEP, FER, SAL, GMIN, GMAX"
    ),
    source_version_or_reference=(
        "FAO EcoCrop Database / FAO GAEZ (Global Agro-Ecological Zoning) v4 biophysical descriptors"
    ),
    notes=(
        "Ecological parameters define macro-scale biophysical tolerance boundaries. "
        "Microclimatic conditions, cultivar genetics, seed varieties, irrigation practices, "
        "and pest/disease pressures may alter local performance."
    ),
)

# Authoritative FAO ECOCROP profiles for all 22 benchmark model crops
FAO_ECOCROP_PROFILES: dict[str, CropEnvironmentalRequirement] = {
    "rice": CropEnvironmentalRequirement(
        crop_name="rice",
        scientific_name="Oryza sativa",
        ecocrop_code=1574,
        common_name="rice",
        temp_min_c=10.0,
        temp_opt_min_c=20.0,
        temp_opt_max_c=30.0,
        temp_max_c=36.0,
        rainfall_min_mm=1000.0,
        rainfall_opt_min_mm=1500.0,
        rainfall_opt_max_mm=2000.0,
        rainfall_max_mm=4000.0,
        soil_ph_min=4.5,
        soil_ph_opt_min=5.5,
        soil_ph_opt_max=7.0,
        soil_ph_max=9.0,
        soil_textures_optimal=["heavy", "medium", "light"],
        soil_textures_absolute=["heavy", "medium", "light"],
        soil_drainage_optimal="poorly (saturated >50% of year)",
        soil_drainage_absolute="poorly (saturated >50% of year)",
        soil_depth_optimal="medium (50-150 cm)",
        soil_depth_absolute="medium (50-150 cm)",
        soil_fertility_optimal="high",
        soil_salinity_optimal="low (<4 dS/m)",
        crop_cycle_min_days=80,
        crop_cycle_max_days=180,
        provenance=DEFAULT_ECOCROP_PROVENANCE,
    ),
    "maize": CropEnvironmentalRequirement(
        crop_name="maize",
        scientific_name="Zea mays",
        ecocrop_code=2175,
        common_name="maize",
        temp_min_c=10.0,
        temp_opt_min_c=18.0,
        temp_opt_max_c=33.0,
        temp_max_c=47.0,
        rainfall_min_mm=400.0,
        rainfall_opt_min_mm=600.0,
        rainfall_opt_max_mm=1200.0,
        rainfall_max_mm=1800.0,
        soil_ph_min=4.5,
        soil_ph_opt_min=5.0,
        soil_ph_opt_max=7.0,
        soil_ph_max=8.5,
        soil_textures_optimal=None,  # Left None as documented in source FAO table
        soil_textures_absolute=None,
        soil_drainage_optimal=None,
        soil_drainage_absolute=None,
        soil_depth_optimal="medium (50-150 cm)",
        soil_depth_absolute="medium (50-150 cm)",
        soil_fertility_optimal="high",
        soil_salinity_optimal="low (<4 dS/m)",
        crop_cycle_min_days=65,
        crop_cycle_max_days=365,
        provenance=DEFAULT_ECOCROP_PROVENANCE,
    ),
    "chickpea": CropEnvironmentalRequirement(
        crop_name="chickpea",
        scientific_name="Cicer arietinum",
        ecocrop_code=2479,
        common_name="chickpea",
        temp_min_c=7.0,
        temp_opt_min_c=15.0,
        temp_opt_max_c=29.0,
        temp_max_c=35.0,
        rainfall_min_mm=300.0,
        rainfall_opt_min_mm=600.0,
        rainfall_opt_max_mm=1000.0,
        rainfall_max_mm=1800.0,
        soil_ph_min=4.7,
        soil_ph_opt_min=6.0,
        soil_ph_opt_max=8.5,
        soil_ph_max=9.5,
        soil_textures_optimal=["heavy", "medium"],
        soil_textures_absolute=["heavy", "medium", "light"],
        soil_drainage_optimal="well (dry spells)",
        soil_drainage_absolute="well (dry spells)",
        soil_depth_optimal="medium (50-150 cm)",
        soil_depth_absolute="medium (50-150 cm)",
        soil_fertility_optimal="moderate",
        soil_salinity_optimal="low (<4 dS/m)",
        crop_cycle_min_days=90,
        crop_cycle_max_days=180,
        provenance=DEFAULT_ECOCROP_PROVENANCE,
    ),
    "kidneybeans": CropEnvironmentalRequirement(
        crop_name="kidneybeans",
        scientific_name="Phaseolus vulgaris",
        ecocrop_code=1668,
        common_name="kidney bean",
        temp_min_c=7.0,
        temp_opt_min_c=16.0,
        temp_opt_max_c=25.0,
        temp_max_c=32.0,
        rainfall_min_mm=300.0,
        rainfall_opt_min_mm=500.0,
        rainfall_opt_max_mm=2000.0,
        rainfall_max_mm=4300.0,
        soil_ph_min=4.0,
        soil_ph_opt_min=5.5,
        soil_ph_opt_max=7.5,
        soil_ph_max=9.0,
        soil_textures_optimal=["medium", "organic"],
        soil_textures_absolute=["heavy", "medium", "light"],
        soil_drainage_optimal="well (dry spells)",
        soil_drainage_absolute="well (dry spells)",
        soil_depth_optimal="medium (50-150 cm)",
        soil_depth_absolute="medium (50-150 cm)",
        soil_fertility_optimal="moderate",
        soil_salinity_optimal="low (<4 dS/m)",
        crop_cycle_min_days=50,
        crop_cycle_max_days=270,
        provenance=DEFAULT_ECOCROP_PROVENANCE,
    ),
    "pigeonpeas": CropEnvironmentalRequirement(
        crop_name="pigeonpeas",
        scientific_name="Cajanus cajan",
        ecocrop_code=576,
        common_name="pigeonpea",
        temp_min_c=10.0,
        temp_opt_min_c=18.0,
        temp_opt_max_c=38.0,
        temp_max_c=45.0,
        rainfall_min_mm=400.0,
        rainfall_opt_min_mm=600.0,
        rainfall_opt_max_mm=1500.0,
        rainfall_max_mm=4000.0,
        soil_ph_min=4.5,
        soil_ph_opt_min=5.0,
        soil_ph_opt_max=7.0,
        soil_ph_max=8.4,
        soil_textures_optimal=["medium", "light"],
        soil_textures_absolute=["heavy", "medium", "light"],
        soil_drainage_optimal="well (dry spells)",
        soil_drainage_absolute="well (dry spells), excessive (dry/moderately dry)",
        soil_depth_optimal="deep (>>150 cm)",
        soil_depth_absolute="medium (50-150 cm)",
        soil_fertility_optimal="moderate",
        soil_salinity_optimal="low (<4 dS/m)",
        crop_cycle_min_days=90,
        crop_cycle_max_days=365,
        provenance=DEFAULT_ECOCROP_PROVENANCE,
    ),
    "mothbeans": CropEnvironmentalRequirement(
        crop_name="mothbeans",
        scientific_name="Vigna aconitifolia",
        ecocrop_code=2524,
        common_name="moth bean",
        temp_min_c=13.0,
        temp_opt_min_c=24.0,
        temp_opt_max_c=32.0,
        temp_max_c=45.0,
        rainfall_min_mm=400.0,
        rainfall_opt_min_mm=500.0,
        rainfall_opt_max_mm=900.0,
        rainfall_max_mm=2500.0,
        soil_ph_min=5.0,
        soil_ph_opt_min=6.5,
        soil_ph_opt_max=7.5,
        soil_ph_max=8.0,
        soil_textures_optimal=["light"],
        soil_textures_absolute=["heavy", "medium", "light"],
        soil_drainage_optimal="well (dry spells)",
        soil_drainage_absolute="well (dry spells)",
        soil_depth_optimal="medium (50-150 cm)",
        soil_depth_absolute="medium (50-150 cm)",
        soil_fertility_optimal="low",
        soil_salinity_optimal="low (<4 dS/m)",
        crop_cycle_min_days=60,
        crop_cycle_max_days=90,
        provenance=DEFAULT_ECOCROP_PROVENANCE,
    ),
    "mungbean": CropEnvironmentalRequirement(
        crop_name="mungbean",
        scientific_name="Vigna radiata",
        ecocrop_code=2150,
        common_name="mungbean",
        temp_min_c=8.0,
        temp_opt_min_c=21.0,
        temp_opt_max_c=36.0,
        temp_max_c=40.0,
        rainfall_min_mm=500.0,
        rainfall_opt_min_mm=650.0,
        rainfall_opt_max_mm=900.0,
        rainfall_max_mm=1250.0,
        soil_ph_min=4.3,
        soil_ph_opt_min=5.5,
        soil_ph_opt_max=6.2,
        soil_ph_max=8.3,
        soil_textures_optimal=["medium", "organic"],
        soil_textures_absolute=["heavy", "medium", "light"],
        soil_drainage_optimal="well (dry spells)",
        soil_drainage_absolute="well (dry spells)",
        soil_depth_optimal="medium (50-150 cm)",
        soil_depth_absolute="medium (50-150 cm)",
        soil_fertility_optimal="moderate",
        soil_salinity_optimal="low (<4 dS/m)",
        crop_cycle_min_days=50,
        crop_cycle_max_days=120,
        provenance=DEFAULT_ECOCROP_PROVENANCE,
    ),
    "blackgram": CropEnvironmentalRequirement(
        crop_name="blackgram",
        scientific_name="Vigna mungo",
        ecocrop_code=2149,
        common_name="black gram",
        temp_min_c=8.0,
        temp_opt_min_c=22.0,
        temp_opt_max_c=35.0,
        temp_max_c=40.0,
        rainfall_min_mm=530.0,
        rainfall_opt_min_mm=650.0,
        rainfall_opt_max_mm=900.0,
        rainfall_max_mm=2430.0,
        soil_ph_min=4.5,
        soil_ph_opt_min=5.5,
        soil_ph_opt_max=6.5,
        soil_ph_max=7.5,
        soil_textures_optimal=["heavy", "medium"],
        soil_textures_absolute=["heavy", "medium"],
        soil_drainage_optimal="well (dry spells)",
        soil_drainage_absolute="well (dry spells)",
        soil_depth_optimal="deep (>>150 cm)",
        soil_depth_absolute="deep (>>150 cm)",
        soil_fertility_optimal="high",
        soil_salinity_optimal="low (<4 dS/m)",
        crop_cycle_min_days=60,
        crop_cycle_max_days=130,
        provenance=DEFAULT_ECOCROP_PROVENANCE,
    ),
    "lentil": CropEnvironmentalRequirement(
        crop_name="lentil",
        scientific_name="Lens culinaris",
        ecocrop_code=7209,
        common_name="lentil",
        temp_min_c=5.0,
        temp_opt_min_c=15.0,
        temp_opt_max_c=29.0,
        temp_max_c=32.0,
        rainfall_min_mm=250.0,
        rainfall_opt_min_mm=600.0,
        rainfall_opt_max_mm=1000.0,
        rainfall_max_mm=2500.0,
        soil_ph_min=4.5,
        soil_ph_opt_min=5.5,
        soil_ph_opt_max=7.5,
        soil_ph_max=8.2,
        soil_textures_optimal=["heavy", "medium"],
        soil_textures_absolute=["heavy", "medium", "light"],
        soil_drainage_optimal="well (dry spells)",
        soil_drainage_absolute="well (dry spells)",
        soil_depth_optimal="medium (50-150 cm)",
        soil_depth_absolute="medium (50-150 cm)",
        soil_fertility_optimal="moderate",
        soil_salinity_optimal="low (<4 dS/m)",
        crop_cycle_min_days=70,
        crop_cycle_max_days=240,
        provenance=DEFAULT_ECOCROP_PROVENANCE,
    ),
    "pomegranate": CropEnvironmentalRequirement(
        crop_name="pomegranate",
        scientific_name="Punica granatum",
        ecocrop_code=1829,
        common_name="pomegranate",
        temp_min_c=8.0,
        temp_opt_min_c=23.0,
        temp_opt_max_c=32.0,
        temp_max_c=40.0,
        rainfall_min_mm=400.0,
        rainfall_opt_min_mm=900.0,
        rainfall_opt_max_mm=1200.0,
        rainfall_max_mm=4200.0,
        soil_ph_min=5.8,
        soil_ph_opt_min=6.5,
        soil_ph_opt_max=7.5,
        soil_ph_max=8.5,
        soil_textures_optimal=["heavy", "medium"],
        soil_textures_absolute=["heavy", "medium", "light"],
        soil_drainage_optimal="well (dry spells)",
        soil_drainage_absolute="well (dry spells)",
        soil_depth_optimal="deep (>>150 cm)",
        soil_depth_absolute="deep (>>150 cm)",
        soil_fertility_optimal="high",
        soil_salinity_optimal="low (<4 dS/m)",
        crop_cycle_min_days=180,
        crop_cycle_max_days=365,
        provenance=DEFAULT_ECOCROP_PROVENANCE,
    ),
    "banana": CropEnvironmentalRequirement(
        crop_name="banana",
        scientific_name="Musa acuminata",
        ecocrop_code=7848,
        common_name="banana",
        temp_min_c=12.0,
        temp_opt_min_c=23.0,
        temp_opt_max_c=33.0,
        temp_max_c=42.0,
        rainfall_min_mm=650.0,
        rainfall_opt_min_mm=1200.0,
        rainfall_opt_max_mm=3600.0,
        rainfall_max_mm=5000.0,
        soil_ph_min=4.0,
        soil_ph_opt_min=5.5,
        soil_ph_opt_max=7.5,
        soil_ph_max=8.4,
        soil_textures_optimal=["medium", "organic"],
        soil_textures_absolute=["heavy", "medium", "light"],
        soil_drainage_optimal="well (dry spells)",
        soil_drainage_absolute="well (dry spells)",
        soil_depth_optimal="deep (>>150 cm)",
        soil_depth_absolute="deep (>>150 cm)",
        soil_fertility_optimal="high",
        soil_salinity_optimal="low (<4 dS/m)",
        crop_cycle_min_days=180,
        crop_cycle_max_days=365,
        provenance=DEFAULT_ECOCROP_PROVENANCE,
    ),
    "mango": CropEnvironmentalRequirement(
        crop_name="mango",
        scientific_name="Mangifera indica",
        ecocrop_code=1416,
        common_name="mango",
        temp_min_c=8.0,
        temp_opt_min_c=24.0,
        temp_opt_max_c=30.0,
        temp_max_c=48.0,
        rainfall_min_mm=300.0,
        rainfall_opt_min_mm=600.0,
        rainfall_opt_max_mm=1500.0,
        rainfall_max_mm=2600.0,
        soil_ph_min=4.3,
        soil_ph_opt_min=5.5,
        soil_ph_opt_max=7.5,
        soil_ph_max=8.5,
        soil_textures_optimal=["medium", "light"],
        soil_textures_absolute=["heavy", "medium", "light"],
        soil_drainage_optimal="well (dry spells)",
        soil_drainage_absolute="well (dry spells)",
        soil_depth_optimal="deep (>>150 cm)",
        soil_depth_absolute="deep (>>150 cm)",
        soil_fertility_optimal="moderate",
        soil_salinity_optimal="low (<4 dS/m)",
        crop_cycle_min_days=150,
        crop_cycle_max_days=365,
        provenance=DEFAULT_ECOCROP_PROVENANCE,
    ),
    "grapes": CropEnvironmentalRequirement(
        crop_name="grapes",
        scientific_name="Vitis vinifera",
        ecocrop_code=2160,
        common_name="grape",
        temp_min_c=10.0,
        temp_opt_min_c=18.0,
        temp_opt_max_c=30.0,
        temp_max_c=38.0,
        rainfall_min_mm=400.0,
        rainfall_opt_min_mm=700.0,
        rainfall_opt_max_mm=850.0,
        rainfall_max_mm=1200.0,
        soil_ph_min=4.5,
        soil_ph_opt_min=5.5,
        soil_ph_opt_max=7.5,
        soil_ph_max=8.5,
        soil_textures_optimal=["medium", "organic"],
        soil_textures_absolute=["heavy", "medium", "light"],
        soil_drainage_optimal="well (dry spells)",
        soil_drainage_absolute="well (dry spells)",
        soil_depth_optimal="deep (>>150 cm)",
        soil_depth_absolute="deep (>>150 cm)",
        soil_fertility_optimal="moderate",
        soil_salinity_optimal="low (<4 dS/m)",
        crop_cycle_min_days=160,
        crop_cycle_max_days=270,
        provenance=DEFAULT_ECOCROP_PROVENANCE,
    ),
    "watermelon": CropEnvironmentalRequirement(
        crop_name="watermelon",
        scientific_name="Citrullus lanatus",
        ecocrop_code=708,
        common_name="watermelon",
        temp_min_c=15.0,
        temp_opt_min_c=20.0,
        temp_opt_max_c=35.0,
        temp_max_c=40.0,
        rainfall_min_mm=400.0,
        rainfall_opt_min_mm=500.0,
        rainfall_opt_max_mm=700.0,
        rainfall_max_mm=1800.0,
        soil_ph_min=5.5,
        soil_ph_opt_min=6.0,
        soil_ph_opt_max=7.0,
        soil_ph_max=7.5,
        soil_textures_optimal=["medium"],
        soil_textures_absolute=["light"],
        soil_drainage_optimal="well (dry spells)",
        soil_drainage_absolute="excessive (dry/moderately dry)",
        soil_depth_optimal="deep (>>150 cm)",
        soil_depth_absolute="medium (50-150 cm)",
        soil_fertility_optimal="high",
        soil_salinity_optimal="low (<4 dS/m)",
        crop_cycle_min_days=None,  # Documented as unrecorded (0) in EcoCrop database
        crop_cycle_max_days=None,
        provenance=DEFAULT_ECOCROP_PROVENANCE,
    ),
    "muskmelon": CropEnvironmentalRequirement(
        crop_name="muskmelon",
        scientific_name="Cucumis melo",
        ecocrop_code=815,
        common_name="muskmelon",
        temp_min_c=9.0,
        temp_opt_min_c=18.0,
        temp_opt_max_c=30.0,
        temp_max_c=35.0,
        rainfall_min_mm=900.0,
        rainfall_opt_min_mm=1000.0,
        rainfall_opt_max_mm=1300.0,
        rainfall_max_mm=2500.0,
        soil_ph_min=5.0,
        soil_ph_opt_min=6.0,
        soil_ph_opt_max=7.5,
        soil_ph_max=8.7,
        soil_textures_optimal=["medium", "organic"],
        soil_textures_absolute=["heavy", "medium", "light"],
        soil_drainage_optimal="well (dry spells)",
        soil_drainage_absolute="well (dry spells)",
        soil_depth_optimal="medium (50-150 cm)",
        soil_depth_absolute="medium (50-150 cm)",
        soil_fertility_optimal="moderate",
        soil_salinity_optimal="low (<4 dS/m)",
        crop_cycle_min_days=50,
        crop_cycle_max_days=120,
        provenance=DEFAULT_ECOCROP_PROVENANCE,
    ),
    "apple": CropEnvironmentalRequirement(
        crop_name="apple",
        scientific_name="Malus domestica",
        ecocrop_code=1407,
        common_name="apple",
        temp_min_c=8.0,
        temp_opt_min_c=14.0,
        temp_opt_max_c=27.0,
        temp_max_c=33.0,
        rainfall_min_mm=500.0,
        rainfall_opt_min_mm=700.0,
        rainfall_opt_max_mm=2500.0,
        rainfall_max_mm=3200.0,
        soil_ph_min=4.5,
        soil_ph_opt_min=6.0,
        soil_ph_opt_max=7.0,
        soil_ph_max=8.0,
        soil_textures_optimal=["medium", "light"],
        soil_textures_absolute=["heavy", "medium", "light"],
        soil_drainage_optimal="well (dry spells)",
        soil_drainage_absolute="well (dry spells)",
        soil_depth_optimal="deep (>>150 cm)",
        soil_depth_absolute="deep (>>150 cm)",
        soil_fertility_optimal="high",
        soil_salinity_optimal="low (<4 dS/m)",
        crop_cycle_min_days=180,
        crop_cycle_max_days=320,
        provenance=DEFAULT_ECOCROP_PROVENANCE,
    ),
    "orange": CropEnvironmentalRequirement(
        crop_name="orange",
        scientific_name="Citrus sinensis",
        ecocrop_code=720,
        common_name="sweet orange",
        temp_min_c=13.0,
        temp_opt_min_c=20.0,
        temp_opt_max_c=30.0,
        temp_max_c=38.0,
        rainfall_min_mm=450.0,
        rainfall_opt_min_mm=1200.0,
        rainfall_opt_max_mm=2000.0,
        rainfall_max_mm=2700.0,
        soil_ph_min=4.0,
        soil_ph_opt_min=5.0,
        soil_ph_opt_max=6.0,
        soil_ph_max=8.3,
        soil_textures_optimal=["medium", "light"],
        soil_textures_absolute=["heavy", "medium", "light"],
        soil_drainage_optimal="well (dry spells)",
        soil_drainage_absolute="well (dry spells)",
        soil_depth_optimal="deep (>>150 cm)",
        soil_depth_absolute="medium (50-150 cm)",
        soil_fertility_optimal="moderate",
        soil_salinity_optimal="low (<4 dS/m)",
        crop_cycle_min_days=180,
        crop_cycle_max_days=365,
        provenance=DEFAULT_ECOCROP_PROVENANCE,
    ),
    "papaya": CropEnvironmentalRequirement(
        crop_name="papaya",
        scientific_name="Carica papaya",
        ecocrop_code=630,
        common_name="papaya",
        temp_min_c=12.0,
        temp_opt_min_c=21.0,
        temp_opt_max_c=30.0,
        temp_max_c=44.0,
        rainfall_min_mm=1000.0,
        rainfall_opt_min_mm=1500.0,
        rainfall_opt_max_mm=2500.0,
        rainfall_max_mm=3000.0,
        soil_ph_min=4.5,
        soil_ph_opt_min=5.5,
        soil_ph_opt_max=7.0,
        soil_ph_max=8.0,
        soil_textures_optimal=["medium", "organic"],
        soil_textures_absolute=["heavy", "medium", "light"],
        soil_drainage_optimal="well (dry spells)",
        soil_drainage_absolute="well (dry spells), excessive (dry/moderately dry)",
        soil_depth_optimal="deep (>>150 cm)",
        soil_depth_absolute="medium (50-150 cm)",
        soil_fertility_optimal="high",
        soil_salinity_optimal="low (<4 dS/m)",
        crop_cycle_min_days=330,
        crop_cycle_max_days=365,
        provenance=DEFAULT_ECOCROP_PROVENANCE,
    ),
    "coconut": CropEnvironmentalRequirement(
        crop_name="coconut",
        scientific_name="Cocos nucifera",
        ecocrop_code=744,
        common_name="coconut",
        temp_min_c=14.0,
        temp_opt_min_c=22.0,
        temp_opt_max_c=34.0,
        temp_max_c=38.0,
        rainfall_min_mm=650.0,
        rainfall_opt_min_mm=1200.0,
        rainfall_opt_max_mm=2400.0,
        rainfall_max_mm=4000.0,
        soil_ph_min=4.3,
        soil_ph_opt_min=5.0,
        soil_ph_opt_max=8.0,
        soil_ph_max=8.7,
        soil_textures_optimal=["medium", "light"],
        soil_textures_absolute=["heavy", "medium", "light"],
        soil_drainage_optimal="well (dry spells)",
        soil_drainage_absolute="well (dry spells)",
        soil_depth_optimal="deep (>>150 cm)",
        soil_depth_absolute="medium (50-150 cm)",
        soil_fertility_optimal="moderate",
        soil_salinity_optimal="low (<4 dS/m)",
        crop_cycle_min_days=270,
        crop_cycle_max_days=365,
        provenance=DEFAULT_ECOCROP_PROVENANCE,
    ),
    "cotton": CropEnvironmentalRequirement(
        crop_name="cotton",
        scientific_name="Gossypium hirsutum",
        ecocrop_code=1160,
        common_name="cotton",
        temp_min_c=15.0,
        temp_opt_min_c=22.0,
        temp_opt_max_c=36.0,
        temp_max_c=42.0,
        rainfall_min_mm=450.0,
        rainfall_opt_min_mm=750.0,
        rainfall_opt_max_mm=1200.0,
        rainfall_max_mm=1500.0,
        soil_ph_min=5.0,
        soil_ph_opt_min=6.0,
        soil_ph_opt_max=7.5,
        soil_ph_max=9.5,
        soil_textures_optimal=["heavy", "medium"],
        soil_textures_absolute=["heavy", "medium", "light", "organic"],
        soil_drainage_optimal="well (dry spells)",
        soil_drainage_absolute="well (dry spells)",
        soil_depth_optimal="deep (>>150 cm)",
        soil_depth_absolute="deep (>>150 cm)",
        soil_fertility_optimal="moderate",
        soil_salinity_optimal="low (<4 dS/m)",
        crop_cycle_min_days=150,
        crop_cycle_max_days=200,
        provenance=DEFAULT_ECOCROP_PROVENANCE,
    ),
    "jute": CropEnvironmentalRequirement(
        crop_name="jute",
        scientific_name="Corchorus capsularis",
        ecocrop_code=4849,
        common_name="white jute",
        temp_min_c=13.0,
        temp_opt_min_c=20.0,
        temp_opt_max_c=37.0,
        temp_max_c=45.0,
        rainfall_min_mm=900.0,
        rainfall_opt_min_mm=1500.0,
        rainfall_opt_max_mm=3000.0,
        rainfall_max_mm=3600.0,
        soil_ph_min=5.0,
        soil_ph_opt_min=6.5,
        soil_ph_opt_max=7.0,
        soil_ph_max=8.6,
        soil_textures_optimal=["heavy", "medium"],
        soil_textures_absolute=["heavy", "medium", "light"],
        soil_drainage_optimal="well (dry spells)",
        soil_drainage_absolute="well (dry spells)",
        soil_depth_optimal="medium (50-150 cm)",
        soil_depth_absolute="medium (50-150 cm)",
        soil_fertility_optimal="high",
        soil_salinity_optimal="low (<4 dS/m)",
        crop_cycle_min_days=80,
        crop_cycle_max_days=150,
        provenance=DEFAULT_ECOCROP_PROVENANCE,
    ),
    "coffee": CropEnvironmentalRequirement(
        crop_name="coffee",
        scientific_name="Coffea arabica",
        ecocrop_code=749,
        common_name="arabica coffee",
        temp_min_c=10.0,
        temp_opt_min_c=14.0,
        temp_opt_max_c=28.0,
        temp_max_c=34.0,
        rainfall_min_mm=750.0,
        rainfall_opt_min_mm=1400.0,
        rainfall_opt_max_mm=2300.0,
        rainfall_max_mm=4200.0,
        soil_ph_min=4.3,
        soil_ph_opt_min=5.5,
        soil_ph_opt_max=7.0,
        soil_ph_max=8.4,
        soil_textures_optimal=["medium", "organic"],
        soil_textures_absolute=["medium", "light"],
        soil_drainage_optimal="well (dry spells)",
        soil_drainage_absolute="well (dry spells)",
        soil_depth_optimal="deep (>>150 cm)",
        soil_depth_absolute="deep (>>150 cm)",
        soil_fertility_optimal="high",
        soil_salinity_optimal="low (<4 dS/m)",
        crop_cycle_min_days=210,
        crop_cycle_max_days=330,
        provenance=DEFAULT_ECOCROP_PROVENANCE,
    ),
}


class CropRequirementRepository:
    """Thread-safe registry for authoritative crop environmental requirements."""

    def __init__(self, profiles: dict[str, CropEnvironmentalRequirement] | None = None) -> None:
        """Initialize repository with FAO ECOCROP profiles or custom map."""
        self._profiles: dict[str, CropEnvironmentalRequirement] = (
            copy.deepcopy(profiles) if profiles is not None else copy.deepcopy(FAO_ECOCROP_PROFILES)
        )

    def get_requirement(self, crop_name: str) -> CropEnvironmentalRequirement | None:
        """Retrieve requirement profile for a crop name (case-insensitive)."""
        return self._profiles.get(crop_name.strip().lower())

    def list_supported_crops(self) -> list[str]:
        """Return list of all supported crop identifiers."""
        return sorted(list(self._profiles.keys()))

    def register_requirement(self, requirement: CropEnvironmentalRequirement) -> None:
        """Register or override a crop requirement profile (useful for testing)."""
        self._profiles[requirement.crop_name.strip().lower()] = copy.deepcopy(requirement)

    def remove_requirement(self, crop_name: str) -> None:
        """Remove a requirement profile (useful for simulating missing profiles in tests)."""
        key = crop_name.strip().lower()
        if key in self._profiles:
            del self._profiles[key]


# Global singleton instance
crop_requirement_repository = CropRequirementRepository()
